# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 13:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(max_length=100, verbose_name='Должность')),
                ('address', models.CharField(max_length=100, verbose_name='Адрес')),
                ('phone', models.CharField(max_length=100, verbose_name='Телефон')),
                ('email', models.EmailField(max_length=100, verbose_name='E-mail')),
                ('site', models.CharField(max_length=100, verbose_name='Сайт')),
                ('about', models.TextField(blank=True, null=True, verbose_name='О себе')),
            ],
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('working_time', models.CharField(max_length=100, verbose_name='Ссылка')),
                ('duties', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('technologies', models.TextField(blank=True, null=True, verbose_name='Технологии')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('link', models.CharField(max_length=100, verbose_name='Ссылка')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('link', models.CharField(max_length=100, verbose_name='Ссылка')),
                ('duties', models.TextField(blank=True, null=True, verbose_name='Обязанности')),
                ('technologies', models.TextField(blank=True, null=True, verbose_name='Технологии')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Organization', verbose_name='Заказчик')),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название')),
                ('perсent', models.IntegerField(verbose_name='Процент владения')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='main.Employee', verbose_name='Работник')),
            ],
        ),
        migrations.AddField(
            model_name='experience',
            name='organization',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='main.Organization', verbose_name='Организация'),
        ),
    ]
