# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-04-20 13:52
from __future__ import unicode_literals

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_photo_path, verbose_name='Фото'),
        ),
        migrations.AddField(
            model_name='project',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to=main.models.get_project_img_path, verbose_name='Картинка'),
        ),
        migrations.AlterField(
            model_name='experience',
            name='working_time',
            field=models.CharField(max_length=100, verbose_name='Время работы'),
        ),
    ]
